### PR TITLE
tests: Improve stability of Subscribe tests

### LINKED ISSUE #6399: Flaky subscribe test
## Issue Description

Sometimes there is a test failure in CI:
```
13> #115 failed: Subscribe_test.cpp(1053)
/usr/local/include/c++/15.2.0/bits/stl_vector.h:1370: constexpr std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::back() [with _Tp = std::tuple<int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, int>; _Alloc = std::allocator<std::tuple<int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, int> >; reference = std::tuple<int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, int>&]: Assertion '!this->empty()' failed.
```
[An example of such failure in CI](https://github.com/XRPLF/rippled/actions/runs/22214422460/job/64255136642#step:20:2998).

## Steps to Reproduce

It's not obvious so far how to reproduce this,  but it looks like the failure happens when using gcc 15 on Linux in debug more with code coverage.

## Expected Result

Test passes.

## Actual Result

Sometimes test fails.

### PR DESCRIPTION
**Pull request by kuznetsss**
## High Level Overview of Change

This PR improves stability of Subscribe tests.

Fixes #6399.

### Context of Change

Subscribe tests were flaky because each test performs some operations (e.g. sends transactions) and waits for messages to appear in subscription with 100ms timeout. If tests are slow (because compiled in debug or the machine is slow) some of them could fail. This PR adds an attempt to synchronise background `Env`'s thread and test's thread by ensuring that all the scheduled operations  are started before test's thread starts to wait for a websocket message. This is done by limiting IO threads of the app inside `Env` to `1` and adding a synchronisation barrier after closing ledger.

### Type of Change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Refactor (non-breaking change that only restructures code)
- [ ] Performance (increase or change in throughput and/or latency)
- [x] Tests (you added tests for code that already exists, or your new feature included in this PR)
- [ ] Documentation update
- [ ] Chore (no impact to binary, e.g. `.gitignore`, formatting, dropping support for older tooling)
- [ ] Release

### API Impact

- [ ] Public API: New feature (new methods and/or new fields)
- [ ] Public API: Breaking change (in general, breaking changes should only impact the next api_version)
- [ ] `libxrpl` change (any change that may affect `libxrpl` or dependents of `libxrpl`)
- [ ] Peer protocol change (must be backward compatible or bump the peer protocol version)

### CODE REVIEW

File: src/test/jtx/Env.h [hunk 1]
```diff
@@ -393,6 +393,44 @@ class Env
...
+    */
+    [[nodiscard]] bool
+    syncClose(std::chrono::system_clock::duration timeout = std::chrono::seconds{1})
+    {
+        auto const result = close();
+        std::promise<void> server_barrier;
+        boost::asio::post(app().getIOContext(), [&]() { server_barrier.set_value(); });
+        auto const status = server_barrier.get_future().wait_for(timeout);
+        return result && status == std::future_status::ready;
+    }
```
[the remark this answers is not in the document]
Comment (kuznetsss) [reply src/test/jtx/Env.h]: Fixed

**Review by godexsoft — APPROVED** [review]
Seems like this relies on the fact we have one thread in tests. If it changes there may be issues but for now this is best we can do by the looks of it 👍

**Comment by kuznetsss** [comment]
@godexsoft, you are right and it turned out that the application was not single threaded. I've added an assert into `syncClose()` and enforced the application to have only 1 IO thread in these tests.

**Review by a1q123456 — APPROVED** [review]
May be a good approach. We can merge it and see if it works.

File: src/test/jtx/Env.h [hunk 2]
```diff
@@ -393,6 +394,49 @@ class Env
...
+                false otherwise
+    */
+    [[nodiscard]] bool
+    syncClose(std::chrono::system_clock::duration timeout = std::chrono::seconds{1})
+    {
+        XRPL_ASSERT(
+            app().getNumberOfThreads() == 1,
+            "syncClose() is only useful on an application with a single thread");
+        auto const result = close();
+        auto server_barrier = std::make_shared<std::promise<void>>();
```
Comment (godexsoft) [inline src/test/jtx/Env.h]: nit: Don't know if `xrpld` uses this style or camelCase but i guess camelCase should be preferred here

File: src/test/jtx/Env.h [hunk 3]
```diff
@@ -393,6 +394,49 @@ class Env
...
+        auto future = server_barrier->get_future();
+        boost::asio::post(
```
Comment (godexsoft) [inline src/test/jtx/Env.h]: Wasn't there a util we made to post instead of using asio directly?

**Review by godexsoft — COMMENTED** [review]
Leaving few nits 👍

File: src/test/jtx/Env.h (hunk 3 above)
Comment (kuznetsss) [reply src/test/jtx/Env.h]: I think that was for `spawn()`, not `post()`

File: src/test/jtx/Env.h (hunk 2 above)
Comment (kuznetsss) [reply src/test/jtx/Env.h]: @copilot, can you fix this?

Comment (kuznetsss) [reply src/test/jtx/Env.h]: Fixed
