### PR TITLE
fix: Make assorted RPC fixes

### LINKED ISSUE #6759: AccountChannels: missing type validation on destination_account parameter
AccountChannels: missing type validation on destination_account parameter

**Severity**: LOW  

The doAccountChannels handler calls params[jss::destination_account].asString() at line 77 without checking isString() first. If a non-string value is provided, jsoncpp may produce unexpected results.

**Root cause**: Line 77: strDst = params[jss::destination_account].asString();

### LINKED ISSUE #6762: AccountInfo: gravatar URL uses HTTP instead of HTTPS
AccountInfo: gravatar URL uses HTTP instead of HTTPS

**Severity**: LOW  

The injectSLE function constructs a gravatar URL using HTTP (line 46), exposing the email hash over an unencrypted connection. The code itself contains a TODO comment acknowledging this: 'VFALCO TODO ... shouldn't this be https?'

**Root cause**: Line 46: jv[jss::urlgravatar] = str(boost::format("http://www.gravatar.com/avatar/%s") % md5);

`src/xrpld/rpc/handlers/account/AccountInfo.cpp:43-47`
```cpp
std::string md5 = strHex(makeSlice(b));
boost::to_lower(md5);
// VFALCO TODO Give a name and move this constant
//             to a more visible location. Also
//             shouldn't this be https?
jv[jss::urlgravatar] = str(boost::format("http://www.gravatar.com/avatar/%s") % md5);
```

**Exploit scenario**: Any application consuming the urlgravatar field and making HTTP requests would expose the email hash to network observers via unencrypted traffic.

**Invariant gap**: HTTPS should be used for external URLs. The code acknowledges this in a TODO comment.

**Suggested fix**: Change 'http://' to 'https://' in the gravatar URL format string.

### PR DESCRIPTION
**Pull request by mvadari**
## High Level Overview of Change

- `account_channels`: The `destination_account` field now returns an error if the value is not a string.
- `subscribe`: The `taker` field in the `books` array now returns an error if the value is not a string.
- `account_info`: The `urlgravatar` field now uses HTTPS instead of HTTP.
- `ledger`: The `full`, `accounts`, `transactions`, `expand`, `binary`, `owner_funds`, and `queue` fields now return an error if the value is not a boolean.
- `ledger_data`: The `binary` field now returns an error if the value is not a boolean.
- `submit`: The `fail_hard` field now returns an error if the value is not a boolean.
- `subscribe`: The `taker` field in the `books` array now returns `actMalformed` instead of `badIssuer` if the value is not a valid account.
- `noripple_check`: Changed bitwise `&` to logical `&&` in several places where booleans were being combined
- Role.cpp — Fixed a bug in forwardedFor() where the fallback position returned when no comma/semicolon delimiter was found was computed incorrectly as it->value().size() - forStr.size() (relative to the start of the whole header) instead of remaining (relative to where found points, after "for="). This could cause truncated or over-read IP addresses from the Forwarded header.
- Removed some dead code in the transaction signing code

### Context of Change

AI code review

Fixes #6759
Fixes #6762 

### Type of Change

- [x] Bug fix (non-breaking change which fixes an issue)

### API Impact

Basically only validation changes, the API Changelog has been updated.

## Test Plan

Everything added has tests.

### CODE REVIEW

File: src/test/app/PayChan_test.cpp [hunk 1]
```diff
@@ -984,6 +984,24 @@ struct PayChan_test : public beast::unit_test::suite
             testInvalidAccountParam(Json::Value(Json::objectValue));
             testInvalidAccountParam(Json::Value(Json::arrayValue));
         }
+        {
+            // test destination_account non-string
+            auto testInvalidDestAccountParam = [&](auto const& param) {
+                Json::Value params;
+                params[jss::account] = alice.human();
+                params[jss::destination_account] = param;
+                auto jrr = env.rpc("json", "account_channels", to_string(params))[jss::result];
```
Comment (godexsoft) [inline src/test/app/PayChan_test.cpp]: nit: Can probably be const

File: src/test/rpc/Submit_test.cpp [hunk 2]
```diff
@@ -0,0 +1,91 @@
...
+
+        // Valid boolean values should work (not return invalidParams)
+        {
+            JTx jt = env.jt(pay(alice, bob, XRP(1)));
+            auto const txBlob = strHex(jt.stx->getSerializer().slice());
+
+            Json::Value params;
+            params[jss::tx_blob] = txBlob;
+            params[jss::fail_hard] = true;
+            auto jrr = env.rpc("json", "submit", to_string(params))[jss::result];
```
Comment (godexsoft) [inline src/test/rpc/Submit_test.cpp]: nit: const

File: src/test/rpc/Submit_test.cpp [hunk 3]
```diff
@@ -0,0 +1,91 @@
...
+            BEAST_EXPECT(!jrr.isMember(jss::error) || jrr[jss::error] != "invalidParams");
+        }
+        {
+            JTx jt = env.jt(pay(alice, bob, XRP(1)));
+            auto const txBlob = strHex(jt.stx->getSerializer().slice());
+
+            Json::Value params;
+            params[jss::tx_blob] = txBlob;
+            params[jss::fail_hard] = false;
+            auto jrr = env.rpc("json", "submit", to_string(params))[jss::result];
```
Comment (godexsoft) [inline src/test/rpc/Submit_test.cpp]: nit: const

File: src/test/rpc/Subscribe_test.cpp [hunk 4]
```diff
@@ -772,6 +768,51 @@ class Subscribe_test : public beast::unit_test::suite
...
+            // invalid taker - not a string
+            {
+                Json::Value jv;
+                jv[jss::books] = Json::arrayValue;
+                jv[jss::books][0u] = Json::objectValue;
+                jv[jss::books][0u][jss::taker_pays] =
+                    Account{"gateway"}["USD"](1).value().getJson(JsonOptions::include_date);
+                jv[jss::books][0u][jss::taker_gets][jss::currency] = "XRP";
+                jv[jss::books][0u][jss::taker] = 1;
+                auto jr = wsc->invoke(method, jv)[jss::result];
```
Comment (godexsoft) [inline src/test/rpc/Subscribe_test.cpp]: nit: const here and below

File: src/xrpld/rpc/detail/Role.cpp [hunk 5]
```diff
@@ -252,12 +252,12 @@ forwardedFor(http_request_type const& request)
 
         // We found a "for=".  Scan for the end of the IP address.
         std::size_t const pos = [&found, &it]() {
-            std::size_t pos =
-                std::string_view(found, it->value().end() - found).find_first_of(",;");
+            auto const remaining = static_cast<std::size_t>(it->value().end() - found);
+            std::size_t pos = std::string_view(found, remaining).find_first_of(",;");
```
Comment (godexsoft) [inline src/xrpld/rpc/detail/Role.cpp]: nit: can also be const

File: src/xrpld/rpc/handlers/NoRippleCheck.cpp [hunk 6]
```diff
@@ -104,14 +104,14 @@ doNoRippleCheck(RPC::JsonContext& context)
 
     bool bDefaultRipple = sle->getFieldU32(sfFlags) & lsfDefaultRipple;
 
-    if (bDefaultRipple & !roleGateway)
+    if (bDefaultRipple && !roleGateway)
```
Comment (godexsoft) [inline src/xrpld/rpc/handlers/NoRippleCheck.cpp]: Good

**Review by godexsoft — CHANGES_REQUESTED** [review]
Leaving some nits 👍

File: src/xrpld/rpc/detail/Role.cpp [hunk 7]
```diff
@@ -253,7 +257,7 @@ forwardedFor(http_request_type const& request)
         // We found a "for=".  Scan for the end of the IP address.
         std::size_t const pos = [&found, &it]() {
             auto const remaining = static_cast<std::size_t>(it->value().end() - found);
-            std::size_t pos = std::string_view(found, remaining).find_first_of(",;");
+            std::size_t const pos = std::string_view(found, remaining).find_first_of(",;");
```
Comment (godexsoft) [inline src/xrpld/rpc/detail/Role.cpp]: nit: Could combine this into the condition with a `;` in between

File: src/xrpld/rpc/handlers/ledger/Ledger.cpp [hunk 8]
```diff
@@ -44,7 +44,8 @@ LedgerHandler::check()
         return Status::OK;
     };
 
-    bool full, transactions, accounts, expand, binary, owner_funds, queue;
+    bool full = false, transactions = false, accounts = false, expand = false, binary = false,
```
Comment (godexsoft) [inline src/xrpld/rpc/handlers/ledger/Ledger.cpp]: nit: Personally i'm not a fan of multiple declarations in one place like this.. but seeing that none of these could be `const` perhaps this is ok

File: src/xrpld/rpc/handlers/orderbook/GetAggregatePrice.cpp [hunk 9]
```diff
@@ -217,6 +218,7 @@ doGetAggregatePrice(RPC::JsonContext& context)
         return result;
     }
 
+    // Get the ledger
```
Comment (godexsoft) [inline src/xrpld/rpc/handlers/orderbook/GetAggregatePrice.cpp]: nit: Does this comment help?

**Review by godexsoft — APPROVED** [review]
Left a few more nits but feel free to ignore 👍

File: src/xrpld/rpc/handlers/orderbook/GetAggregatePrice.cpp (hunk 9 above)
Comment (mvadari) [reply src/xrpld/rpc/handlers/orderbook/GetAggregatePrice.cpp]: Merge artifact, removed

Comment (mvadari) [reply src/xrpld/rpc/handlers/orderbook/GetAggregatePrice.cpp]: 1a66f8eb6b983dc945eea7e7e6d7205cbc8c19bb

File: src/xrpld/rpc/handlers/ledger/Ledger.cpp (hunk 8 above)
Comment (mvadari) [reply src/xrpld/rpc/handlers/ledger/Ledger.cpp]: 1a66f8eb6b983dc945eea7e7e6d7205cbc8c19bb

File: src/xrpld/rpc/detail/Role.cpp (hunk 7 above)
Comment (mvadari) [reply src/xrpld/rpc/detail/Role.cpp]: 1a66f8eb6b983dc945eea7e7e6d7205cbc8c19bb

File: API-CHANGELOG.md [hunk 10]
```diff
@@ -40,6 +40,14 @@ This section contains changes targeting a future version.
 - Peer Crawler: The `port` field in `overlay.active[]` now consistently returns an integer instead of a string for outbound peers. [#6318](https://github.com/XRPLF/rippled/pull/6318)
 - `ping`: The `ip` field is no longer returned as an empty string for proxied connections without a forwarded-for header. It is now omitted, consistent with the behavior for identified connections. [#6730](https://github.com/XRPLF/rippled/pull/6730)
```
[the remark this answers is not in the document]
Comment (mvadari) [reply API-CHANGELOG.md:41]: This is just wrong

File: src/xrpld/rpc/handlers/ledger/Ledger.cpp [hunk 11]
```diff
@@ -42,27 +42,56 @@ Status
...
 {
     auto const& params = context_.params;
-    bool const needsLedger = params.isMember(jss::ledger) || params.isMember(jss::ledger_hash) ||
-        params.isMember(jss::ledger_index);
-    if (!needsLedger)
-        return Status::OK;
 
-    if (auto s = lookupLedger(ledger_, context_, result_))
-        return s;
+    auto getBool = [&](Json::StaticString const& field, bool& out) -> Status {
```
Comment (kuznetsss) [inline src/xrpld/rpc/handlers/ledger/Ledger.cpp]: Could we avoid `bool& out` here? For example would `Expected<bool, Status>` work?
Then the later code could be changed to something like:
```cpp
bool const full = getBool(jss::full);
if (!full.has_value()) return full.error();
```
This will allow to make all the bools const and will make it less likely to use wrong bool somewhere.

Comment (mvadari) [reply src/xrpld/rpc/handlers/ledger/Ledger.cpp]: That doesn't work since `full` would have to be type `Expected<bool, Status>`.

I'm not opposed to making this type of change, but the naive implementation would IMO make the code much messier.

Comment (kuznetsss) [reply src/xrpld/rpc/handlers/ledger/Ledger.cpp]: Could you please explain why `full` couldn't be `Expected<bool, Status>`?
It is used in 2 places, but we will simply replace `full` to `*full` because `if (!full.has_value())` is already checked. 
Sorry, I made a mistake in the original example, it should be:
```cpp
auto const full = getBool(jss::full);
if (!full.has_value()) return full.error();
```
and later either
```cpp
options_ = (*full ? LedgerFill::full : 0) | (*expand ? LedgerFill::expand : 0) |
```
or 
```cpp
options_ = (full.value() ? LedgerFill::full : 0) | (expand.value() ? LedgerFill::expand : 0) |
```

Comment (mvadari) [reply src/xrpld/rpc/handlers/ledger/Ledger.cpp]: 91202cd95c6e0dde375273e9245a85ba5e030232

**Review by kuznetsss — APPROVED** [review]

File: src/xrpld/rpc/handlers/subscribe/Subscribe.cpp [hunk 12]
```diff
@@ -248,9 +248,11 @@ doSubscribe(RPC::JsonContext& context)
 
             if (j.isMember(jss::taker))
             {
+                if (!j[jss::taker].isString())
+                    return rpcError(rpcACT_MALFORMED);
```
Comment (bthomee) [inline src/xrpld/rpc/handlers/subscribe/Subscribe.cpp:252]: Elsewhere you used `return RPC::expected_field_error`, and here you return an `rpcError`. Can these made be consistent or is there a good reason to keep them different?

Comment (mvadari) [reply src/xrpld/rpc/handlers/subscribe/Subscribe.cpp:252]: This is an account-specific error, so it made more sense to use it here.
