### PR TITLE
fix: Change AMMClawback return code to tecNO_PERMISSION

### LINKED ISSUE #6922: AMMClawback preclaim returns tesSUCCESS instead of tecNO_PERMISSION for unauthorized clawback
## Summary

AMMClawback preclaim returns tesSUCCESS instead of tecNO_PERMISSION for unauthorized clawback.

## Details

In AMMClawback::preclaim, when featureMPTokensV2 is NOT enabled, if the issuer does NOT have the AllowTrustLineClawback flag set or HAS the NoFreeze flag set, the function returns tesSUCCESS instead of tecNO_PERMISSION. The comment on line 104-105 explicitly says 'return no permission' but the code returns success. This causes the transaction to proceed through doApply, which performs the actual clawback by: (1) withdrawing the holder's LP token position from the AMM pool, (2) transferring the withdrawn assets from the holder to the issuer via directSendNoFee. The original code (before MPTokensV2 refactoring) correctly returned tecNO_PERMISSION. The refactoring introduced tesSUCCESS by mistake. Comparing with Clawback.cpp (line 92-95) and VaultClawback.cpp (lines 192-199), which both correctly return tecNO_PERMISSION for the same check, confirms this is a bug.

**Root cause**: Line 108 in AMMClawback.cpp returns tesSUCCESS where it should return tecNO_PERMISSION. This causes the preclaim to pass when the issuer lacks clawback authorization, allowing doApply to execute the unauthorized clawback. The early return at line 108 also skips the subsequent checkClawAsset validation (lines 111-134) that would correctly return tecNO_PERMISSION.

`src/libxrpl/tx/transactors/dex/AMMClawback.cpp:101-109`
```cpp
std::uint32_t const issuerFlagsIn = sleIssuer->getFieldU32(sfFlags);
if (!ctx.view.rules().enabled(featureMPTokensV2))
{
    // If AllowTrustLineClawback is not set or NoFreeze is set, return no
    // permission
    if (((issuerFlagsIn & lsfAllowTrustLineClawback) == 0u) ||
        ((issuerFlagsIn & lsfNoFreeze) != 0u))
        return tesSUCCESS;
}
```

**Exploit scenario**: 1. An AMM pool exists for IOU_A/XRP where IOU_A issuer does NOT have AllowTrustLineClawback flag set.
2. featureAMMClawback is enabled but featureMPTokensV2 is NOT yet enabled.
3. Alice has deposited into this AMM pool and holds LP tokens worth significant value.
4. The IOU_A issuer submits an AMMClawback transaction targeting Alice's LP position.
5. Preclaim at line 106-108 checks: issuer does NOT have AllowTrustLineClawback → condition is true → returns tesSUCCESS (bug!).
6. doApply executes applyGuts which: (a) withdraws Alice's entire LP position from the AMM (burning her LP tokens, sending IOU_A and XRP to Alice), (b) transfers IOU_A from Alice to the issuer via directSendNoFee.
7. Result: The issuer successfully claws back IOU_A from Alice's AMM position without ever having AllowTrustLineClawback permission.

**Financial impact**: Attacker (any IOU issuer) can steal the full value of any holder's LP position in AMM pools containing their issued token. The stolen amount equals the holder's proportional share of the issuer's asset in the pool. For large pools this could be millions of tokens.

**Invariant gap**: No invariant checks clawback authorization. The ValidAMM invariant checker only validates mathematical properties (sqrt(A*B) >= LP), not authorization.

**Suggested fix**: Change line 108 from 'return tesSUCCESS;' to 'return tecNO_PERMISSION;' to match the comment and the pattern used in Clawback.cpp and VaultClawback.cpp.

---

## Impact

Branch: [`ripple/attackathon-april-2026`](https://github.com/XRPLF/rippled/tree/ripple/attackathon-april-2026)

### PR DESCRIPTION
**Pull request by gregtatcam**
## High Level Overview of Change

Change AMMClawback return code to tecNO_PERMISSION on AllowTrustLineClawback and NoFreeze check.

### Context of Change

Change tesSUCCESS to tecNO_PERMISSION.

## Test Plan

Extend AMMClawback unit-test with featureMPTokensV2 disabled.

### CODE REVIEW

File: src/test/app/AMMClawback_test.cpp [hunk 1]
```diff
@@ -2491,10 +2491,14 @@ class AMMClawback_test : public beast::unit_test::suite
         FeatureBitset const all =
             jtx::testable_amendments() - featureSingleAssetVault - featureLendingProtocol;
 
-        testInvalidRequest();
+        testInvalidRequest(all);
```
Comment (mvadari) [inline src/test/app/AMMClawback_test.cpp:2494]: Should this be in the for loop below? Should we have such tests for all the AMM/DEX tests files?

**Review by yinyiqian1 — APPROVED** [review]
LGTM

**Review by shawnxie999 — APPROVED** [review]

File: src/test/app/AMMClawback_test.cpp (hunk 1 above)
Comment (gregtatcam) [reply src/test/app/AMMClawback_test.cpp:2494]: I don't think so. It doesn't need testing with other amendments disabled.

The following tests would have to be extended to test for featureMPTokenV2 disabled: AMM, AMMExtended, Check, Flow, Offer, Path. It's a lot of tests and might significantly increase the overall unit-tests execution time. It still might be worth doing. It'll be a lot of changes in these tests so it's worth having another PR.
